import {photos,niches,videos,services,gallery,socials} from './content.js?v=20261004-corrections';
export const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function photo(key,sizes='(min-width: 900px) 35vw, 80vw',className=''){
 const p=photos[key];
 if(!p)return `<img class="${className}" src="${esc(key)}" alt="" loading="lazy" width="900" height="1200">`;
 return `<img class="${className}" src="/assets/photos/liza-${p.id}-960.webp" srcset="/assets/photos/liza-${p.id}-480.webp 480w, /assets/photos/liza-${p.id}-960.webp 960w, /assets/photos/liza-${p.id}-1440.webp 1440w" sizes="${sizes}" width="900" height="1200" loading="lazy" decoding="async" alt="${esc(p.alt)}">`;
}
const label=(n,name)=>`<p class="eyebrow micro">${n} / ${name}</p>`;
function About(){return `<section class="about about-original section" id="about"><div class="wrap"><div class="section-topline micro"><span>01 / Обо мне</span></div><div class="about-layout"><div class="about-collage reveal"><figure class="about-photo">${photo('summer')}</figure><span class="about-stamp" aria-hidden="true">about<br><i>me</i></span><span class="about-caption handwritten">это я, без сценария</span></div><div class="about-copy reveal"><h2>Давайте<br><em>знакомиться!</em></h2><p class="about-lead">Я Лиза — лайфстайл<br>и UGC-креатор.</p><p>Создаю живой, эстетичный и нативный контент о красоте, стиле, повседневной жизни и маленьких вещах, которые делают её интереснее.</p><p>Мне важно, чтобы реклама не выбивалась из контента, а становилась его естественной частью. Поэтому я стараюсь не просто показать продукт, а придумать историю и подачу, через которые он действительно заинтересует аудиторию.</p><blockquote>Эстетика, естественность,<br><span class="handwritten">ощущение разговора с подругой.</span></blockquote></div></div></div><div class="bridge-film film" aria-hidden="true">${['beauty','street','cafe','mirror','flowers','summer','portrait','fashion'].map(k=>photo(k,'160px')).join('')}<span class="micro">BEAUTY / FASHION / LIFE</span></div></section>`}
function Contents(){
 const object=(name,file)=>`<span class="vinyl-prop prop-${name}" aria-hidden="true"><img src="/assets/decor/${file}.webp" alt="" loading="lazy" decoding="async"></span>`;
 return `<section class="contents section vinyl-section" id="contents" aria-labelledby="contents-title"><div class="vinyl-stage"><h2 id="contents-title">CONTENTS</h2><div class="vinyl-disc"><img class="vinyl-physical" src="/assets/vinyl.webp" width="1100" height="1100" alt="Розовая виниловая пластинка" loading="lazy"><nav class="vinyl-navigation" aria-label="Разделы портфолио">${[['about','Обо мне'],['contact','Контакты'],['niches','Направления'],['work','Работы'],['services','Что я создаю']].map(([id,name],i)=>`<a href="#${id}" class="vinyl-link link-${i}"><small>0${i+1}</small><span>${name}</span></a>`).join('')}</nav></div>${object('phone','objects/retro-phone')}${object('earphones','objects/wired-earphones')}${object('cassette','objects/pink-cassette')}${object('bow','objects/pink-bow')}${object('heart','hearts/heart-doodles')}${object('stars-a','stars/star-trio')}${object('stars-b','stars/star-handdrawn')}${object('stars-c','stars/diamond-sparkles')}${object('stars-d','stars/star-trio')}</div></section>`;
}
function Niches(){
 const lines=(mobile)=>`<svg class="niche-connections ${mobile?'connections-mobile':'connections-desktop'}" viewBox="0 0 1000 ${mobile?'1400':'650'}" preserveAspectRatio="none" aria-hidden="true">${(mobile?['M470 250 Q130 350 245 600','M530 250 Q870 350 755 600','M420 280 Q60 520 245 980','M580 280 Q940 520 755 980','M500 320 L500 1260']:['M430 240 C380 210 350 150 310 150','M430 330 C375 350 365 405 310 405','M575 240 C640 190 665 165 690 165','M575 330 C635 355 660 405 690 405','M500 380 C515 420 490 445 500 500']).map((d,i)=>`<path data-line="${i}" d="${d}" pathLength="1"/>`).join('')}</svg>`;
 return `<section class="niches section" id="niches"><div class="wrap">${label('03','Направления')}<div class="directions-title"><h2>Мои направления</h2></div><div class="directions-map">${lines(false)}${lines(true)}<figure class="niche-portrait"><div class="lace-portrait"><img class="niche-face" src="/assets/editorial/flower-portrait.webp" width="750" height="1000" alt="Лиза в чёрном платье с букетом цветов" loading="lazy"><img class="lace-frame" src="/assets/lace-frame.webp" width="900" height="1200" alt="" loading="lazy" aria-hidden="true"></div></figure>${niches.map(n=>`<article class="niche-orbit orbit-${n.name.toLowerCase()}"><div class="orbit-photo"><img src="/assets/editorial/${n.name.toLowerCase()}.webp" alt="${esc(n.imageAlt)}" width="480" height="640" loading="lazy" decoding="async"></div><div class="orbit-copy"><h3>${n.name}</h3><p>${esc(n.description)}</p></div></article>`).join('')}</div></div></section>`;
}
function Work(){return `<section class="work section" id="work"><div class="wrap">${label('04','Работы / Selected UGC')}<div class="work-heading"><h2>Смотреть.<br>Чувствовать.</h2><p class="handwritten">ещё один кадр,<br>и ещё один…</p></div>${videos.some(v=>!v.src)?'<p class="work-draft">Здесь скоро появятся 12 видео.<br>Пока — кадры Лизы и превью будущих работ.</p>':''}<div class="reels-wall"><div class="wall-label micro">КОНТАКТНЫЙ ЛИСТ / 001</div><div class="video-grid">${videos.map((v,i)=>`<article class="video-card"><div class="video-mount"><button class="video-preview" data-video="${i}" aria-label="${esc(v.title)}${v.src?' — смотреть видео':' — открыть превью'}">${photo(v.poster,'(min-width: 900px) 22vw, 30vw')}<span class="video-number micro">${v.id}</span><span class="play-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M9 5 20 12 9 19Z"/></svg></span>${!v.src?'<span class="video-soon">СКОРО</span>':''}</button></div><h3>${esc(v.title)}</h3><p>${esc(v.category)}</p></article>`).join('')}</div></div><div class="content-formats" id="services"><h3>Что я создаю</h3><ul>${services.map(name=>`<li>${esc(name)}</li>`).join('')}</ul></div><p class="work-bottom handwritten">маленькие истории, которые хочется досмотреть</p></div></section>`}
function Contact(){return `<section class="contact section" id="contact"><div class="wrap"><div class="contact-letter paper"><div class="letter-top"><span class="micro">КОМУ: ВАШЕМУ БРЕНДУ<br>ОТ: ЛИЗЫ</span><span class="postage" aria-hidden="true">L.<small>CONTENT<br>WITH LOVE</small></span></div>${label('05','Связаться со мной')}<h2>Давайте создадим<br>что-то классное.</h2><div class="contact-body"><div><p>Готова к сотрудничеству с брендами в нишах бьюти, фешн и лайфстайл.</p><p>Если вам близка моя эстетика и формат контента — буду рада обсудить сотрудничество.</p><div class="social-links">${socials.map(s=>`<a href="${s.href}" ${s.href.startsWith('http')?'target="_blank" rel="noopener noreferrer"':''}><span class="micro">${s.name}</span><span>${s.label}</span></a>`).join('')}</div></div><figure class="contact-photo">${photo('portrait')}<figcaption class="handwritten">на связи,<br>Лиза</figcaption><span class="tape" aria-hidden="true"></span></figure></div><p class="letter-sign handwritten">начнём с вашего сообщения.</p></div><footer><a href="#home" class="wordmark">Л.</a><span class="micro">LIFESTYLE CREATOR & UGC</span><a href="#home">Наверх</a><button id="replay-intro">Открыть письмо</button></footer></div></section>`}
export function mountSections(target){target.innerHTML=[About(),Contents(),Niches(),Work(),Contact()].join('')}
